### ISSUE TITLE
Autofillet mail i intervju->sett opp burde være vektormailen

### ISSUE THREAD

**Issue by sigtot** [vektorprogrammet/vektorprogrammet#1024]
I dag er det den personlige mailen som kommer opp

**Comment by kristandre** [comment]
Er det egentlig poeng i å kunne skrive annen e-postadresse enn hva vi bestemmer som som skal være default?

**Comment by sigtot** [comment]
Nei vi burde vel egentlig fjerne email feltet :+1:

**Comment by kristandre** [comment]
Implemented in #1023
