### ISSUE TITLE
/kontrollpanel/skoleadmin viser alle skoler, både inaktive og aktive

### ISSUE THREAD

**Issue by sigtot** [vektorprogrammet/vektorprogrammet#1040]
![image](https://user-images.githubusercontent.com/5937246/46676372-af5caf80-cbe0-11e8-9660-2cae58f0cd32.png)

**Comment by kristandre** [comment]
Alle skolene er markert som aktive?

**Comment by sigtot** [comment]
Aah :thinking: Hvordan var dette før? Siden tabellen plutselig har alle sammen inne

**Comment by kristandre** [comment]
https://v2.staging.vektorprogrammet.no/kontrollpanel/skoleadmin

**Comment by sigtot** [comment]
Jaja, var ikke noen issue da

**Comment by kristandre** [comment]
Fake news
