### ISSUE TITLE
Email kan ikke autofilles i påmeldingen til interesseliste

### ISSUE THREAD

**Issue by sigtot** [vektorprogrammet/vektorprogrammet#1072]
![image](https://user-images.githubusercontent.com/5937246/47900288-b0e66400-de7c-11e8-9885-d7ee46af8549.png)

**Comment by khejd** [comment]
Etter mye googling har jeg ikke funnet ut av hvordan man kan løse dette. Det virker veldig mystisk. En halvveis løsning er å fjerne autocomplete på det feltet.
