### ISSUE TITLE
Kontrollpanel widget: Undersøkelse

### ISSUE THREAD

**Issue by kristandre** [vektorprogrammet/vektorprogrammet#1136]
En oversikt over alle teamundersøkelser som er åpne for gjennomføring

**Comment by AmiAhm** [comment]
![image](https://user-images.githubusercontent.com/15302672/52089393-bd2eaa00-25ae-11e9-8d45-58cace3b30db.png)
@sigtot @kristandre hvilke har størst potensiale?

**Comment by sigtot** [comment]
Jeg digger nr 1

**Comment by kristandre** [comment]
👈

**Comment by kristandre** [comment]
Hvordan blir det med headeren til nr 1 og innholdet til nr 2?

**Comment by AmiAhm** [comment]
![image](https://user-images.githubusercontent.com/15302672/52108901-ee819700-25fb-11e9-96d4-e73fdc19b110.png)
![image](https://user-images.githubusercontent.com/15302672/52108945-1113b000-25fc-11e9-85a3-9cfc1b2759a8.png)
?

**Comment by kristandre** [comment]
3️⃣
