### ISSUE TITLE
Forhåndsvis-knappen under "sett opp intervju" forblir disabled etter man har trykket en gang på den

### ISSUE THREAD

**Issue by sigtot** [vektorprogrammet/vektorprogrammet#1142]
Related to #1129

**Comment by kristandre** [comment]
Det samme skjer nok på forhåndsvisning av team.

Mulig løsning:
Legge på en klasse `ignore-auto-disable` på disse knappene, og legge til en ekstra sjekk på den i button_deactivator.js
