### ISSUE TITLE
Mine utlegg i kontrollpanelet

### ISSUE THREAD

**Issue by AmiAhm** [vektorprogrammet/vektorprogrammet#1146]
Bør gjøre "mine utlegg" mer synlig i kontrollpanelet

Edit: reformulering

**Comment by sigtot** [comment]
Man kan faktisk det allerede, men det er kanskje ikke helt intuitivt å trykke på profilbildet sitt for å få opp denne menyen. 
![image](https://user-images.githubusercontent.com/5937246/51737148-30ef2500-208c-11e9-951b-db355b3963c3.png)

**Comment by AmiAhm** [comment]
![](https://photos.app.goo.gl/TLnN5NqHUTGDGbzA8)

**Comment by AmiAhm** [comment]
Er ikke helt åpenbart at det er en fold-down meny der. Kanskje gjøre pilene til høyere større og hvite?  Vet ikke om det hadde gjort det nok intuitivt da.

**Comment by sigtot** [comment]
Closer denne siden vi har en link til mine utlegg. Men vi kan evt. prøve å gjøre dropdown-menyen mer tydelig på en eller annen måte.
