### ISSUE TITLE
Feil i attestgenerering når tabellen over skoler blir lang

### ISSUE THREAD

**Issue by sigtot** [vektorprogrammet/vektorprogrammet#1167]
Hvis assistenten har være ute på mange skoler blir tabellen i attesten veldig lang og det dytter logoen ned på side 2 av attesten. Resultater blir ikke så pent:
![image](https://user-images.githubusercontent.com/5937246/52210391-3ec05980-2887-11e9-89e2-4e91f21ef9d4.png)

**Comment by kristandre** [comment]
Fixed in #1199
