### ISSUE TITLE
UTF-8 characters encodes feil i urler i admission notification email

### ISSUE THREAD

**Issue by sigtot** [vektorprogrammet/vektorprogrammet#1200]
Her blir f.eks "Ås" enkodet til %C3%85s
![Screenshot_20190812-120028](https://user-images.githubusercontent.com/5937246/62857912-22e7b580-bcf9-11e9-8547-616629d9d946.png)

**Comment by kristandre** [comment]
Er ikke dette riktig url encoding da? Skrev inn `Ås` i https://www.urlencoder.org/, fikk samme resultat der.

![image](https://user-images.githubusercontent.com/6992505/62860028-3e55bf00-bcff-11e9-867c-684c3f5eeee6.png)

**Comment by sigtot** [comment]
Jo men vi støtter jo https://vektorprogrammet.no/opptak/Ås så det kunne vært fint å ha dette i mailen? Da vil urlen se litt mer "pen" ut og kanskje få fler clicks :grin: 

Kan hende det ikke er verdt bryet da :woman_shrugging:

**Comment by kristandre** [comment]
Spørs om det er så enkelt å få `path`-funksjonen til Twig å ikke encode urlen, og om dette er noe vi egentlig ønsker å gjøre?

Hvis noen har lyst til å prøve seg så er det denne epostmalen det er snakk om: https://github.com/vektorprogrammet/vektorprogrammet/blob/1d63db6a9b7082c2a74be245a81a65c51f323366/app/Resources/views/admission/notification_email.html.twig

**Comment by sigtot** [comment]
Jeg tror dette blir for mye bry uten gevinst, så closer issuet.
