### ISSUE TITLE
En undersøkelse som ikke kan prefikses med /u/ gir en evig 302-loop om man legger inn /u/

### ISSUE THREAD

**Issue by haved** [vektorprogrammet/vektorprogrammet#1224]
Noen undersøkelser har `/undersokelse/u/<id>` i url-en, også når man lenker til dem fra kontrollpanelet. Dersom man ikke tar med `/u/`, redirectes man til en url som har den med.

Andre undersøkelser (f.eks. nummer 5 i dev-databasen) har ikke den /u/, og hvis man prøver å legge den til redirecte den til seg selv.

Expected behaviour:
Ikke ha redirect loop

**Comment by haved** [comment]
Ser ut som problemet er i https://github.com/vektorprogrammet/vektorprogrammet/blob/fa6d4a5ab73109b1604a32f69fca6e7896553c75/src/AppBundle/Controller/SurveyController.php#L448

Skal jeg prøve å gjøre noe med det?
Jeg skjønner ikke helt hva `'survey_show_user'` skal bety når man uansett bare gir en survey_id og ikke en user_id.
@AmiAhm?

**Comment by AmiAhm** [comment]
Ja, løsningen er nok å erstatte alle kall til `redirectToCorrectSurvey(Survey $survey)`
`return $this->redirectToRoute('survey_show', array('id' => $survey->getId())); `
evt.  bare kaste 404

**Comment by AmiAhm** [comment]
Men @haved går raskt å fikse det, så du skal slippe.
