### ISSUE TITLE
Sikkerhetsfeil?

### ISSUE THREAD

**Issue by alexaoh** [vektorprogrammet/vektorprogrammet#1309]
![bilde](https://user-images.githubusercontent.com/47002854/70865855-6fbaf180-1f62-11ea-9032-00172679e3e6.png)

**Comment by sigtot** [comment]
Det var jo rart. Jeg har ingen problemer med https for øyeblikket. Det er lenge til sertifikatet går ut og lenge siden det ble registrert står det:
![image](https://user-images.githubusercontent.com/5937246/70940571-edf2c300-204a-11ea-9fe6-d4084e62e9f3.png)

Har du fortsatt problemer?

**Comment by alexaoh** [comment]
Prøvde igjen nå. Fungerte fint. Aner ikke hva som skjedde sist?
