### ISSUE TITLE
Undersøke hva som skjer med ipinfo.io

### ISSUE THREAD

**Issue by Lundli** [vektorprogrammet/vektorprogrammet#1398]
![image](https://user-images.githubusercontent.com/46197518/94597189-89c58680-028d-11eb-8c36-77ae30c4b4e0.png)

Det er mulig dette er ip.info som har feiler, men det burde undersøkes.

**Comment by AmiAhm** [comment]
Mulig løsning, kanskje verdt å se på om problemet oppstår igjen

![image](https://user-images.githubusercontent.com/15302672/95238588-00243480-080a-11eb-910d-507dff32c3fe.png)

**Comment by AmiAhm** [comment]
Ser ikke ut til å være et problem lenger ^

**Comment by Lundli** [comment]
Lukker denne. Var ipinfo som hadde problemer virker det som.
