### ISSUE TITLE
ReceiptControllerTest lager testfiler på toppnivå og lar dem ligge

### ISSUE THREAD

**Issue by haved** [vektorprogrammet/vektorprogrammet#1428]
Eksempel på filnavn: `recfz7EaW`.

Det virker som om det er en 1x1 pixel 8-bit PNG, basert på `file`-kommandoen.

**Comment by haved** [comment]
NB: Dette problemet oppstår i docker, mulig det kun oppstår der siden funksjonen `sys_get_tmp_dir()` brukes, og den er sannsynligvis et bedre sted når man ikke kjører i docker

**Comment by Lundli** [comment]
Det kan være grunnet Docket ja.
 Jeg har i alle fall aldri opplevd at testen lager testfiler og lar de ligge :thinking: :thinking:

**Comment by Lundli** [comment]
Lukker denne ettersom det kun skjer ved bruk av Docker.
