### ISSUE TITLE
Bruk av Annotation er deprecated

### ISSUE THREAD

**Issue by Lundli** [vektorprogrammet/vektorprogrammet#1430]
Eksempel:
<img src="https://user-images.githubusercontent.com/46197518/95510960-0c99c000-09b7-11eb-8d77-7116f4794bb0.png" width=300>

Filer det gjelder:
<img src="https://user-images.githubusercontent.com/46197518/95513148-225cb480-09ba-11eb-960e-d7ff960f41f8.png" width=350>

Filene i listeformat:
- [x] AccessruleController
- [x] AccountController
- [x] AdmissionAdminController
- [x] AdmissionSubscriberController
- [x] ArticleAdminController
- [x] AssistantController
- [x] CertificateController
- [x] ClientController
- [x] ConfirmationController
- [x] ExecutiveBoardController
- [x] ExistingUserAdmissionController
- [x] InterviewController
- [x] SponsorController
- [x] StandController
- [x] SurveyController
- [x] TeamAdminController
- [x] TeamInterestController
- [x] UserController

**Comment by alexaoh** [comment]
Ref  #1448 (my bad)
