### ISSUE TITLE
<table width="100%" er deprecated

### ISSUE THREAD

**Issue by Lundli** [vektorprogrammet/vektorprogrammet#1438]
`<table width="100%"` er deprecated
Filer:
- [x] assigned_table.html.twig
- [x] assistant_history_table.html.twig
- [x] existing_assistants_applications_table.html.twig
- [x] views/substitute/index.html.twig
- [x] views/participant_history/index.html.twig
- [x] views/admission_admin/assigned_applications/interview_distribution.html.twig
- [x] views/admission_admin/interviewed_applications_table.html.twig
- [x] views/members/members.html.twig
- [x] views/receipt/my_receipts_table.html.twig
- [x] views/school_admin/school_table.html.twig
- [x] views/social_event/social_event_list.html.twig
- [x] views/admission_admin/new_applications/table.html.twig
- [x] views/admission_admin/teaminterest.html.twig
- [x] views/todo_list/todo_list.html.twig
- [x] views/user_admin/user.table.html.twig
- [x] views/team_admin/welcome_google_mail.html.twig
- [x] views/team_admin/welcome_team_membership_mail.html.twig

**Comment by hhtjo** [comment]
`<table class="w-100">` ?
