### ISSUE TITLE
Mellomlagre intervju

### ISSUE THREAD

**Issue by Strauman** [vektorprogrammet/vektorprogrammet#180]
Den som ikke lagre kan,
skriver sine ord i sand.
Ctrl+s før alt forsvinner,
det gjør smarte menn og kvinner!

Ønsker altså mulighet for å mellomlagre intervju. I praksis - en knapp, i tillegg til den nåværende "lagre", med tekst "lagre og send info til assistent".

**Comment by kristandre** [comment]
Liknende funksjonalitet finnes for å sette opp intervju: https://github.com/vektorprogrammet/vektorprogrammet/blob/master/src/AppBundle/Controller/InterviewController.php#L378

**Comment by kristandre** [comment]
Skal få gjort denne i løpet av uka.

**Comment by kristandre** [comment]
Implementert i #428
