### ISSUE TITLE
[Insight] Unused use statement should be avoided - in src/…/Controller/SponsorsController.php, line 7

### ISSUE THREAD

**Issue by kristandre** [vektorprogrammet/vektorprogrammet#286]
**[in src/AppBundle/Controller/SponsorsController.php, line 7](https://github.com/vektorprogrammet/vektorprogrammet/blob/3564c72532535574f8fd1148371be82cc4cad34f/src/AppBundle/Controller/SponsorsController.php#L7)**

> The class `Symfony\Component\HttpFoundation\Response` is declared but never used. You should remove the `use` statement.

```php

namespace AppBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use AppBundle\Form\Type\SponsorType;
use AppBundle\FileSystem\FileUploader;
use AppBundle\Entity\Sponsor;

class SponsorsController extends Controller
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/ec066ae0-5658-4365-af0c-4ab7492d2ad7/analyses/1?status=violations)_

**Comment by jvals** [comment]
Fixed in #312
