### ISSUE TITLE
Samsvar mellom brukere og roller

### ISSUE THREAD

**Issue by jvals** [vektorprogrammet/vektorprogrammet#332]
Stemmer dette, eller er det feil i README?
For eksempel:
admin = ROLE_SUPER_ADMIN
superadmin = ROLE_HIGHEST_ADMIN
![skjermbilde 2016-10-12 kl 14 56 23](https://cloud.githubusercontent.com/assets/6677078/19310785/127de396-908c-11e6-9d11-94bb5a569510.png)

**Comment by jvals** [comment]
Jeg ville lagt ved en label "not important" hvis det fantes 😆

**Comment by aestene** [comment]
Korrekt d der ja, men litt forvirrende at team = admin og admin = superadmin. Tru d va implementert sånn fra starten av, så bli ganske my arbeid å fiks d :)

**Comment by jvals** [comment]
Problemet går dypere enn README med andre ord 😝

**Comment by aestene** [comment]
Ja, e ganske mang testa som må endres hvis den der endres som e ha forstått d. Kjappast veien e kanskje å endre brukernavnet på admin t superadmin, men usikker på kå my som må endres.

**Comment by kristandre** [comment]
Vi burde endre navn på rollene, selv om det innebærer en del arbeid å refaktorisere eksisterende kode.

Forslag:
```
ROLE_ASSISTANT
ROLE_TEAM_MEMBER
ROLE_TEAM_LEADER
ROLE_ADMIN
```

**Comment by kristandre** [comment]
>Jeg ville lagt ved en label "not important" hvis det fantes 😆

Har laget en `Not Important` label nå, men siden disse navnene skaper en del forvirring vil jeg si at denne issuen er litt mer viktig enn `Not Important`.

**Comment by jvals** [comment]
Tanken var at hvis problemet _bare_ lå i README, så hadde problemet vært "Not important".
Men 🎉 for ny label.

**Comment by kristandre** [comment]
Beholder at brukere kan ha flere roller. Gi fornuftige navn på rollene
