### ISSUE TITLE
Automatisk fordeling av assistenter

### ISSUE THREAD

**Issue by jvals** [vektorprogrammet/vektorprogrammet#368]
Branch: [schoolAllocation](https://github.com/vektorprogrammet/vektorprogrammet/tree/SchoolAllocation)
Page: /kontrollpanel/skole/fordeling/allokering

Slik jeg ser det er det to alternativer her,

1. Når siden har blitt lastet inn, så er alle felter fylt med resultatet fra algoritmen.
2. Når siden har blitt lastet inn, så er alle felter tomme eller har en default verdi. Brukeren må trykke på en knapp "Autofordel" for å kjøre algoritmen, som vil fylle ut alle feltene.

Jeg tror at alternativ 1 vil være best her, siden algoritmen fungerer best når den har størst mulig handlingsrom. Hvis brukeren fordeler noen assistenter manuelt _før_ automatisk fordeling, så vil 

1. det manuelle arbeidet gå tapt, eller
2. algoritmen får mindre assistenter å fordele (mindre handlingsrom)

**Comment by kristandre** [comment]
Jeg stemmer for alternativ 1. Men da burde det være mulig for brukeren å velge hvilke assistenter som skal autofordeles før siden lastes.

**Comment by jvals** [comment]
Det kan kanskje gjøres med checkbokser i en egen kolonne i assistenttabellen på 
/kontrollpanel/skole/fordeling/? Så kan man huke av hvem som skal fordeles eller ikke fordeles.
