### ISSUE TITLE
Header/Tekst på allokeringssiden

### ISSUE THREAD

**Issue by jvals** [vektorprogrammet/vektorprogrammet#370]
Branch: [schoolAllocation](https://github.com/vektorprogrammet/vektorprogrammet/tree/SchoolAllocation)
Page: /kontrollpanel/skole/fordeling/allokering

Denne siden trenger en ny header, eller kanskje ingen header i det hele tatt.
Foreløpig står det
### Denne siden skal inneholde allokeringsappen

I tillegg hadde det vært fint med en tekst som forklarer alt som ikke er åpenbart, eller en tekst som introduserer siden generelt. Hvis dere syns at siden er selvforklarende og intuitiv, så trengs ikke dette.

**Comment by kristandre** [comment]
+1 for en liten introduksjonstekst.

**Comment by aestene** [comment]
Enig

**Comment by aestene** [comment]
:smile: 
(Sondre ment min "Enig" va for kjedelig, derav nødvendig med smiley!)
