### ISSUE TITLE
Stedsnavn attester

### ISSUE THREAD

**Issue by aestene** [vektorprogrammet/vektorprogrammet#391]
Når andre regioner oppretter attest for sine assistenter står det "Trondheim" som stedsnavn.

**Comment by kristandre** [comment]
Her burde vi kanskje bruke Department sin adresse, ja. Department har allerede et adressefelt, men det blir kanskje mer fleksibelt om vi deler denne i `postnr`, `by` og `gate/vei`. Så kan vi sende disse til Certificate templaten.

**Comment by aestene** [comment]
Det skal stå Trondheim, NTNU etc for den øverste delen da dette er organisasjonsrelatert. Bare det nederste stedsnavnet som skal endres. Trenger bare "by" isåfall.

**Comment by kristandre** [comment]
Da kan vi beholde adressefeltet, men legge til `by`. Fikser du det?

**Comment by aestene** [comment]
Jepp! Men bli itj gjort firri i jula, må prøv å skap litt forståelse for AlgDat før lørdan 😃
