### ISSUE TITLE
Kan ikke aktivere brukere

### ISSUE THREAD

**Issue by Strauman** [vektorprogrammet/vektorprogrammet#413]
Etter "Rediger aktivitetsnivå->Aktiver bruker -> Ja" skjer ikke selve oppdateringen. Dette forhindrer å kunne gi tidligere assistenter søkemulighet som tidligere assistent.

**Comment by kristandre** [comment]
Fungerer dette nå?

**Comment by Strauman** [comment]
Ser ut til å være i skjønneste orden 👍
