### ISSUE TITLE
Assistenter tildeles ikke brukernavn automatisk

### ISSUE THREAD

**Issue by Strauman** [vektorprogrammet/vektorprogrammet#431]
input text for Brukernavn, i brukerprofil, for (tidligere) assistenter er tom. Ikke kjent hva default brukernavn er, så vi må gjøre det manuelt

**Comment by kristandre** [comment]
Brukernavn skal bli satt til email by default, men pga. en feil en stund tilbake ble ikke dette gjort for alle brukere. Har rettet opp dette for brukerene det gjaldt.
