### ISSUE TITLE
Endring av rettighetnivå

### ISSUE THREAD

**Issue by sondreso** [vektorprogrammet/vektorprogrammet#461]
Brukere skal ikke kunne endre rettighetsnivå på andre som har samme eller høyere rettigheter enn seg selv.

**Comment by sigtot** [comment]
Så vidt jeg skjønner gjelder dette kun for teamleaders? Team members og lavere kan jo ikke endre rettighetsnivå i det hele tatt, og admins skal kunne endre rettighetsnivå for alle. 

Men teamleaders må vel kunne redigere rettighetsnivået til andre teamleaders? Noen må jo kunne gjøre det.
Slik jeg skjønner det trenger vi derfor bare å gjøre slik at teamleaders ikke kan endre rettighetsnivået til admins.
