### ISSUE TITLE
Undersøkelser - Kun vise gjeldende skoler

### ISSUE THREAD

**Issue by aestene** [vektorprogrammet/vektorprogrammet#467]
Kun vise skoler som faktisk har hatt assistenter i det gjeldende semesteret.

**Comment by jvals** [comment]
Det er denne listen det er snakk om?
![image](https://cloud.githubusercontent.com/assets/6677078/23309384/c4b0d5c8-faae-11e6-82ad-1b61a5f42c38.png)
