### ISSUE TITLE
Link på navn i teamsidene

### ISSUE THREAD

**Issue by aestene** [vektorprogrammet/vektorprogrammet#470]
Medlemmer av team skal kunne trykkes på for å gå til profilen

**Comment by kristandre** [comment]
@simon-iversen, hva er status her?

**Comment by simon-iversen** [comment]
Status er at det er mulig å trykke på medlemmene hvis man er innlogget (navnet er en link til profilen), mens hvis man ikke er innlogget så vises navnet bare i vanlig tekst. Prøvde også å laste in URL'en "https://vektorprogrammet.no/profile/177", og da ble jeg redirecta til innlogging, så det er kanskje meningen at man må være innlogget for å se profilene?

**Comment by kristandre** [comment]
Det stemmer at man må være innlogget for å se profiler. Lukker denne issuen siden har blitt implementert :)
