### ISSUE TITLE
Fjerne setId på Newsletter

### ISSUE THREAD

**Issue by kristandre** [vektorprogrammet/vektorprogrammet#473]
Newsletter skal ikke ha en `setId`-funksjon

**Comment by aestene** [comment]
Generell regel? Role.php har en setId å

**Comment by aestene** [comment]
Ligger også en i teamApplication som nok skal fjernes. Ligger også en i User.php

**Comment by kristandre** [comment]
Dette er en generell regel, ja. Alle entities som har autogenerert id, `@ORM\GeneratedValue(strategy="AUTO")`, skal ikke ha en setter
