### ISSUE TITLE
Endre spørsmål for dager i søknad for gamle assistenter

### ISSUE THREAD

**Issue by aestene** [vektorprogrammet/vektorprogrammet#475]
Det skal være "Hvilke dager passer IKKE?"

**Comment by jvals** [comment]
#477

**Comment by jvals** [comment]
Hva skjer med logikken nå?
Svarene mappes fortsatt til "Bra" og "Ikke".

**Comment by jvals** [comment]
I tillegg så er svarene helt iqtest nå som spørsmålet er endra.
![image](https://cloud.githubusercontent.com/assets/6677078/23416586/b6a45a58-fde3-11e6-8d27-112ba78eae17.png)

**Comment by jvals** [comment]
Kanskje bruke en rad med checkbokser, der man bare krysser av de dagene man IKKE kan?

**Comment by jvals** [comment]
😆
