### ISSUE TITLE
Skriv test for visning av opptaksside

### ISSUE THREAD

**Issue by aestene** [vektorprogrammet/vektorprogrammet#479]
Skriv testShow() funksjonen i AdmissionControllerTest.php.
Dette er en grunnleggende oppgave i testing. Funksjonen skal logge inn med en bruker og sjekke at visse faste elementer i testdatabasen befinner seg på side og at siden faktisk laster inn. Se andre lignende tester for andre sider for å få god hjelp!

**Comment by jvals** [comment]
Hva skjedde med denne? Ser ut som at `testShow` ble skrevet i #504, men `testShow` på master er tom.

**Comment by kristandre** [comment]
Ja, #504 ble closed fordi den inneholdt to PRer

**Comment by jvals** [comment]
Jupp, lurte bare på om endringene på testShow noen gang ble overført til en ny PR. Ser at de ligger på branchen `newTestShowAdmissionController` nå.

**Comment by kristandre** [comment]
@thusanarul Hva er status på `newTestShowAdmissionController`?
