### ISSUE TITLE
Slett-knapper synlig for admins på brukersiden

### ISSUE THREAD

**Issue by sigtot** [vektorprogrammet/vektorprogrammet#502]
Knappene skal kun være synlige for superadmins. Endres i twig. Trykker man på knappene (som admin) får man en 500-error, det er derfor ikke et sikkerhetshull.

**Comment by kristandre** [comment]
Burde man ikke egentlig fått en 403 error? En 500 error betyr at det er en case vi ikke har tatt høyde for. Det her burde undersøkes nærmere!
