### ISSUE TITLE
Workhistories for hovedstyret

### ISSUE THREAD

**Issue by aestene** [vektorprogrammet/vektorprogrammet#539]
Fikse slik at arbeidshistorikk fra hovedstyret legges til for de som har det. Hvordan skal dette gjøres?

**Comment by khejd** [comment]
Er dette noe som trengs? Det kan bli vanskelig da medlemmene i Hovedstyret ikke er koblet mot et semester. Medlemmer av Hovedstyret skal heller ikke få autogenererte attester...

**Comment by kristandre** [comment]
Hvor tenker du at arbeidshistorikk skal legges til?
Kontrollpanel - deltakerhistorikk?
Profilen?
Attesten?

**Comment by aestene** [comment]
På generell basis burde den oppføre seg på akkurat samme måte som vanlig teamhistorikk, da både attest, profil og deltakerhistorikk. Angående attest så brukes den automatiske ikke for de fleste i team, så nei det er ikke nødvendig for attest egentlig. 
Behovet ligger først og fremst i at historien om medlemmene i hovedstyret ligger som en del av nettsiden, altså at man kan finne informasjon om hvem som har vært i hovedstyret tilbake i tid på nettsiden istedet for å grave seg ned i driven.

**Comment by kristandre** [comment]
Implemented in #862
