### ISSUE TITLE
Opprett teammedlem for gammelt semester

### ISSUE THREAD

**Issue by aestene** [vektorprogrammet/vektorprogrammet#541]
Virker som om det er en feil ved oppretting av teammedlemmer i gamle semestre der semestret er eldre enn brukeren? Or something like that. Ikke helt sikker på hva som skjer.
Se under

**Comment by jvals** [comment]
![yo](https://cloud.githubusercontent.com/assets/6677078/25290938/5b065e4c-26d0-11e7-8063-1cbb7aa17466.png)

**Comment by sigtot** [comment]
Er dette blitt fikset? Får ikke reprodusert det i hvert fall.

**Comment by kristandre** [comment]
Ser ut som det ble fikset i #630 

https://github.com/vektorprogrammet/vektorprogrammet/commit/8ec70610bc7b4885e55f4bf245dcb0176d208e90#diff-3b2f1134f78eec27fa94dd7a6ea24901L143
