### ISSUE TITLE
'Opprett bruker' til andre departments

### ISSUE THREAD

**Issue by khejd** [vektorprogrammet/vektorprogrammet#544]
På [/kontrollpanel](https://vektorprogrammet.no/kontrollpanel) ->'Ny bruker' kan man legge til ny bruker i et annet department, men på [/kontrollpanel/brukeradmin](https://vektorprogrammet.no/kontrollpanel/brukeradmin) har man ikke det valget. Skal man kunne lage brukere til andre departments?

**Comment by kristandre** [comment]
Det er greit at teammedlemmer kan opprette assistenter, så det burde finnes en link på /kontrollpanel/brukeradmin

**Comment by kristandre** [comment]
Men det bør kanskje begrenses til at de kun kan lage brukere til sin egen department. Det er greit at teamledere kan lage brukere til alle departments (de må lage brukere når vi utvider til nye departments)
