### ISSUE TITLE
Flytte link til 'Vikarer' fra 'Brukere' til 'Opptak og Undersøkelse' i footer.

### ISSUE THREAD

**Issue by khejd** [vektorprogrammet/vektorprogrammet#546]

**Comment by kristandre** [comment]
Flyttet vi ikke nettop vikarer fra 'Brukere' til 'Opptak og Undersøkelse'?

**Comment by khejd** [comment]
Da er det footer linken som må byttes :)

**Comment by kristandre** [comment]
Det begynner å bli mange elementer i kategoriene. Kanskje det er på tide å tenke på om noe bør reorganiseres? Endre, legge til eller fjerne kategorier?

![image](https://cloud.githubusercontent.com/assets/6992505/25293742/7d3300e0-26dc-11e7-97b8-808a0cd355a1.png)
