### ISSUE TITLE
Nyhetsbrev: sett markøren til navn-feltet automatisk

### ISSUE THREAD

**Issue by jvals** [vektorprogrammet/vektorprogrammet#553]
Etter at en person har registrert seg, så må neste person velge navn-feltet før han/hun kan begynne å skrive.

Markøren burde settes til navn-feltet automatisk.

**Comment by kristandre** [comment]
Det er her snakk om autofocus:
https://www.w3schools.com/tags/att_input_autofocus.asp

Burde være en kjapp sak, og bør prioriteres siden det er standperiode nå

**Comment by kristandre** [comment]
```
{{ form_row(form.name, {'attr': {'autofocus': 'autofocus'}}) }}
```

Tar noen på seg denne?

**Comment by aestene** [comment]
E kan godt fiks den :D
