### ISSUE TITLE
Automatisere onboardingprosessen av nye teammedlemmer

### ISSUE THREAD

**Issue by kristandre** [vektorprogrammet/vektorprogrammet#560]
### Mål: Alle stegene som er knyttet til registrering av nye teammedlemmer blir automatisert
___

- Teamleder går til teamet sitt og trykker "legg til medlem", velg:
  - Legg til bruker fra liste
  - Opprett ny bruker

Det nye teammedlemmet får en e-post:
> - Du har blitt lagt til i teamet _Rekruttering_.
> - En ny bruker har blitt opprettet for deg på https://vektorprogrammet.no, følg denne linken for å fullføre registreringen https://vektorprogrammet/bruker/Xjkfi86kjafbau
> - En ny e-postadresse har blitt opprettet for deg:
navn@vektorprogrammet.no, passordet vil alltid være det samme som brukeren din på vektorprogrammet.no. Bruk Vektorprogrammet sin epostklient på https://vektorprogrammet.no/mail, eller følg denne linken for instrukser til å legge til din nye epostadresse i Gmail/Outlook: https://vektorprogrammet.no/epostinstrukser
> - Du vil straks motta en invitasjon til Slack, som er blablabla...
> - Invitasjon to Google Drive
> - Dette kan du gjøre som teammedlem på nettsiden: "Instrukser som er spesifikt for teamet"

Flere steg som trengs?

**Comment by aestene** [comment]
- Tilgang pp Drive

**Comment by sigtot** [comment]
Closer denne nå siden det meste er fikset bortsett fra #978
