### ISSUE TITLE
Receipts: Navn på diverse ting

### ISSUE THREAD

**Issue by kristandre** [vektorprogrammet/vektorprogrammet#568]
`Aktive / eldre` utlegg -> `Nye / refunderte` utlegg ?
`Ferdig`-knapp -> `Refundert`-knapp ?

På utleggssiden:
`Opprett utlegg` -> `Registrer utlegg` ?
`Lagre`-knapp -> `Registrer`/`Be om refusjon` ?

**Comment by sigtot** [comment]
Enig i at dette gjør funksjonaliteten tydeligere.

**Comment by aestene** [comment]
Enig, refundert va forresten et bra ord!
