### ISSUE TITLE
Receipts: Forklaring på utleggssiden

### ISSUE THREAD

**Issue by kristandre** [vektorprogrammet/vektorprogrammet#569]
Det burde stå en liten tekst om hva denne funksjonaliteten gjør og hva man typisk kan be om refusjon for.

**Comment by sigtot** [comment]
Hva slags utgifter kan man egentlig be om refusjon for? Bussbilletter ol. i hvertfall, men jeg kommer ikke på så mange andre gode eksempler. Lunsj?

**Comment by kristandre** [comment]
Denne er ferdig implementert, right?
