### ISSUE TITLE
Receipts: Synlig ID i tabell

### ISSUE THREAD

**Issue by sigtot** [vektorprogrammet/vektorprogrammet#578]
Jeg foreslår at vi viser en synlig ID som hører til hvert utlegg i tabellen. På den måten blir det lettere å referere til et spesifikt utlegg hvis man skulle trenge det.

Eksempler på tilfeller vi kan trenge dette:
* Noen har flere nye utlegg, og vi har spørsmål angående ett av dem
* Noen har flere refunderte utlegg liggende, og det viser seg at det er feil ved ett av dem

Spørsmål: Er det dumt å bruke den innebygde inkrementerende IDen til dette? Det vil kanskje virke rart for de første brukerne å få id 1, 2, 3 osv. Mulig det er mer profesjonelt å generere IDer med et fast antall siffer.

**Comment by kristandre** [comment]
Dette er en god ide! Foreslår at vi generer id med [uniqid()](http://php.net/manual/en/function.uniqid.php) eller liknende
