### ISSUE TITLE
Daglig epost-påminnelse om intervju-invitasjon

### ISSUE THREAD

**Issue by kristandre** [vektorprogrammet/vektorprogrammet#607]
Sette opp at det sendes epost-påminnelse hver dag kl 12.00 til de som ikke har svart på intervju-invitasjon

**Comment by sigtot** [comment]
Burde vi sende dem med tekstmeldinger og, eller blir det litt for spamish?

**Comment by kristandre** [comment]
Kan sende sms én gang hvis det er < 24 timer igjen?
