### ISSUE TITLE
Lage standalone vikarer

### ISSUE THREAD

**Issue by sigtot** [vektorprogrammet/vektorprogrammet#632]
Vi burde kunne opprette vikarer direkte uten at de trenger å gå gjennom søke-/intervjuprosessen. Tar gjerne i mot tips for hvordan den praktiske utførelsen burde være. 

Skal vi ha en opprett-vikar knapp på vikarsiden, som oppretter en helt ny bruker der og da? Eller kanskje det holder å opprette en bruker under brukersiden, så lenge vi implementerer en måte å gjøre denne til vikar direkte fra vikarsiden – f.eks med en dropdown med alle brukerne i eller et søkefelt.

Et problem vi må takle er hvor vi skal putte dataene for hvilke dager som passer. De ligger i dag under application. Kunne vi fått det til uten å gå igjennom en application? Eller skal vi kanskje opprette en søknad under-the-hood som inneholder de dataene? 

Her er det mange valg som må tas.

**Comment by kristandre** [comment]
Kan kanskje gjenbruke noe fra "Rediger vikar"?

![image](https://user-images.githubusercontent.com/6992505/30202677-876f6ea2-947f-11e7-912d-867ca53af2b1.png)
