### ISSUE TITLE
Mangler backend-validering av input

### ISSUE THREAD

**Issue by kristandre** [vektorprogrammet/vektorprogrammet#678]
Det mangler validering på en del entities, som Length, Not Blank etc. Burde gå gjennom alle entities og sjekke at de valideres riktig. Burde også skrive tester som sjekker valideringen.

**Comment by sigtot** [comment]
Closer denne nå, siden hele nettsiden ble gjennomgått i #898 og de fleste (forhåpentligvis) av valideringsfeilene da ble luket ut. Men vi burde fortsatt skrive tester (#903).
