### ISSUE TITLE
Back buttons eller breadcrumb navigation

### ISSUE THREAD

**Issue by sigtot** [vektorprogrammet/vektorprogrammet#683]
Flere sider i kontrollpanelet kunne trengt en knapp som tar brukeren tilbake til oversikten. På utleggsida, f.eks, hvis man åpner utleggene til en person, er eneste veien tilbake til utlegg-oversikten å bruke tilbake-knappen i browseren. Dette er spesielt dumt når man submitter en form, siden tilbakeknappen da tar deg tilbake til samme siden, før formen ble submittet. Tilbakeknappen reloader heller ikke siden, så endringene man nettopp gjorde, vises ikke. 

Foreslår en av følgende løsninger:
* En "tilbake til oversikten"-knapp (lett)
* Breadcrumb navigation (vanskelig)

Breadcrumbs er ønskelig, men blir vanskelig å implementere. Skal dette implementeres burde det vel være overalt, slik at brukeren alltid kan se hvor de er i nettsidestrykturen. Det kan kanskje hentes direkte ut i fra pathen?

Problemet gjelder for de fleste sider som har en oversikt -> underoversikt -> enkeltelementer
Noen eksempler:
* Receipts -> individual receipts -> endre status
* Opptak -> fordelt -> sett opp
* Attest -> endre signatur
* Skole -> tildel skole

**Comment by sigtot** [comment]
Forslag til breadcrumb design
![breadcrumbs forslag](https://user-images.githubusercontent.com/5937246/32235414-b7ae8a80-be5f-11e7-9711-6f17f3eb490c.png)

**Comment by kristandre** [comment]
Implemented in #1023
