### ISSUE TITLE
Receipts: 500 error when creating a receipt without uploading image

### ISSUE THREAD

**Issue by sigtot** [vektorprogrammet/vektorprogrammet#689]
**Error:** `Call to a member function getMimeType() on null`
*in src/AppBundle/Service/FileUploader.php at line 67*
```php
{
        $file = $this->getFileFromRequest($request);
        $mimeType = $file->getMimeType();
        $fileType = explode('/', $mimeType)[0];
        if ($fileType === 'image') {
            return $this->uploadFile($file, $this->receiptFolder);
```

**Possible fix:** [`9730594`](https://github.com/vektorprogrammet/vektorprogrammet/pull/688/commits/9730594e0fe321a09602a5e9fe95d7521b3a201c)

**Comment by Lundli** [comment]
Lukker denne, da det ikke er mulig å opprette utlegg uten kvittering (grunnet fix ref. i issue-beskrivelsen).
