### ISSUE TITLE
ReceiptControllerTest failer på Windows

### ISSUE THREAD

**Issue by jvals** [vektorprogrammet/vektorprogrammet#715]

**Comment by kristandre** [comment]
Hvilken test?

**Comment by jvals** [comment]
@duchavo @khejd

**Comment by kristandre** [comment]
Ble det fikset i #708?

**Comment by jvals** [comment]
Det kan hende. Noe av feilmeldingen var at den fikk "error 500" når den forventet "error 302", har det noen sammenheng med #708 ?

**Comment by kristandre** [comment]
Nei, det har ikke noen sammenheng med #708. Hos meg kjører testene fint på master. Er det en annen branch det er snakk om?

**Comment by jvals** [comment]
To forskjellige branches (Issue636 og englishToLanguage) basert på master.

**Comment by jvals** [comment]
[Could not reproduce](https://xkcd.com/583/)

**Comment by khejd** [comment]
![image](https://user-images.githubusercontent.com/15192747/36435280-89d5928e-1661-11e8-9704-18ae72bfadd8.png)

**Comment by kristandre** [comment]
:)
