### ISSUE TITLE
2. intervjuer

### ISSUE THREAD

**Issue by jvals** [vektorprogrammet/vektorprogrammet#742]
Et intervju har to intervjuere, men i dag er det bare første intervjuer som kan åpne intervjusiden.
En mulighet er å la team-medlemmer sette seg opp som andre intervjuer.
En annen løsning er å la første intervjuer velge andre intervjuer, men det blir raskt mer jobb enn å bare dele en pc under intervju.

**Comment by kristandre** [comment]
Stemmer for begge. Første intervjuer kan legge til en 2. intervjuer. Hvis et fordelt intervju mangler 2. intervjuer så kan et teammedlem selv melde seg på som 2. intervjuer.

Tilleggsforslag: når et teammedlem melder seg selv som 2. intervjuer så sendes det en epost til 1. intervjuer.
