### ISSUE TITLE
Utvide teaminteresselisten til å inneholde team

### ISSUE THREAD

**Issue by jvals** [vektorprogrammet/vektorprogrammet#757]
Under intervju blir alle assistenter spurt om de kan tenke seg å bli med i team, og dem som sier ja blir satt på en interesseliste for team. Denne listen bør inneholde info om hvilke team søkeren syns virker spennende, da det vil gjøre det enklere å drive målrettet rekruttering til team.

**Comment by kristandre** [comment]
Hva er status her? Skal dette være ferdig før opptaksperioden H2018?

**Comment by kristandre** [comment]
@vildesba @taphan Får dere tid til å fullføre denne før semeteret er over? Hvis ikke, kan dere pushe branchen til GitHub slik at @jvals kan ta over? :)
