### ISSUE TITLE
Redesign: Fixed header på mobil

### ISSUE THREAD

**Issue by kristandre** [vektorprogrammet/vektorprogrammet#781]

**Comment by sigtot** [comment]
Mye av innholdet havner oppå headeren slik: 
![image](https://user-images.githubusercontent.com/5937246/37710914-712c0f3c-2d0f-11e8-9c18-0350c4583941.png)
Tror det kommer av at en del av bootstrapklassene, blant annet `col-x` er `position: relative`, og de blir da stacket oppå headeren selv om den er `position:fixed`. Jeg la derfor på `z-index: 1` i [c5b46b7](https://github.com/vektorprogrammet/vektorprogrammet/commit/c5b46b783201371b4de7a0a8f543c49a7d612999) for å fikse problemet. Hvis noen har et bedre forslag så rop ut, men jeg closer issuet for nå. 

Måtte også legge på en spacer div med samme innhold som headeren for å pushe resten av innholdet på siden nedover. Tenkte det var lurere enn å legge på en hardkoda `margin-top` for å få riktig spacing.
