### ISSUE TITLE
Lengdebegrensning på passord

### ISSUE THREAD

**Issue by sigtot** [vektorprogrammet/vektorprogrammet#796]
Ser ut som vi mangler max length på passord her og der. Det funker helt fint å sette passordet til et kort og greit passord, men hvis jeg setter passordet til 1107 a-er gjennom glemt-passord eller i profilen, så får jeg ikke logget inn igjen med det samme 1107-bokstaver lange passordet. Testet det bare på redesign, men regner med det gjelder i master og. 

Viktig at lengdevalideringen er lik overalt, og helst implementert på frontend og.

**Comment by ojmioen** [comment]
Fikk (med litt assistanse) til å fikse det:)
