### ISSUE TITLE
User onDelete cascade

### ISSUE THREAD

**Issue by kristandre** [vektorprogrammet/vektorprogrammet#818]
Når en bruker slettes må assistanthistories, applicaitons, interviews, workhistories osv. som er knyttet til brukeren også slettes

**Comment by sigtot** [comment]
Gsuite brukeren burde vel også slettes

**Comment by sondreso** [comment]
Det er mye som må avgjøres før man kan slette Gsuite brukeren, for eksempel om man skal overføre epost og filer i privat drive til andre (og eventuelt til hvem). Sånn foreløpig ville jeg ikke slettet Gsuite brukeren når brukeren slettes fra nettsiden, og ihvertfall ikke gjøre dette automatisk!

**Comment by kristandre** [comment]
Alternativt så kan vi (automatisk) deaktivere login (i SsoCobtrolleren) til gsuite for brukere som ikke lengre er aktive i team. Hvis vi trenger å reaktivere de senere så vil ingen data fra Gmail/drive gå tapt. Det kan da lages en liste over alle deaktiverte gsuite-brukere slik at en admin manuelt kan gå inn og rydde opp e-post og drive.

**Comment by sondreso** [comment]
Ja, tror det er beste løsningen!
