### ISSUE TITLE
Autofill intervjuoppsett

### ISSUE THREAD

**Issue by kristandre** [vektorprogrammet/vektorprogrammet#964]
Når man setter opp intervjuer for søkere vil man som regel bruke samme rommet til mange intervjuer etter hverandre. For å gjøre utfyllingsjobben enklere kan `rom`, `campus`, `link til kart` settes til å være samme som forrige oppsett brukeren lagde. Tidspunktet kan også automatisk settes til `forrige tidspunkt +20 min`.

**Comment by sigtot** [comment]
Burde dette løses med bare litt javascript, der feltene lagres i localstorage/sessionstorage? Skal vi evt. også finne en måte å slippe å hardkode `+20 min` på?

**Comment by kristandre** [comment]
Tror det blir enklere å gjøre det i backend siden vi bare kan fylle inn data til Application objektet før det sendes til form typen. Hvis vi skal gjøre det med javascript så må det litt "hacking" til for å få det til å funke bra med form input generert av symfony.

Kan ha antall minutter som en parameter i parameters.yml, eller regne ut forskjellen på de to forrige oppsettene. En annen mulighet er å ha det i databasen et sted. F.eks. at hver department kan bestemme standard varighet på intervjuene sine.

**Comment by sigtot** [comment]
Ja tenkte mest så den som setter opp intervjuer kan justere selv hvor lang intervjutid de ønsker

**Comment by kristandre** [comment]
Kanskje vi kan ha en ny klasse, `UserOptions`, der vi kan putte forskjellige preferanser for hver bruker. Varighet på intervju, hvilken side det redirectes til etter innlogging, personverinnstillinger osv.

**Comment by sigtot** [comment]
Kjempeidé! Det vil sikkert åpne for mange andre muligheter og
