### ISSUE TITLE
Synliggjøre IT-teamet i kontrollpanelet

### ISSUE THREAD

**Issue by sigtot** [vektorprogrammet/vektorprogrammet#972]
Vi må gjøre det mer tydelig for regionene at IT-teamet kan hjelpe til med problemer folk har på nettsiden og at de og har innflytelse for hvordan vi utvikler siden.

**Comment by kristandre** [comment]
Forslag:

#### En egen supportside i kontrollpanelet der medlemmer kan:
1. Sende spørsmål om ting de lurer på hvordan fungerer i kontrollpanelet
2. Sende inn forslag til features

Feedbacken blir sendt til IT på e-post og på Slack med `@channel`, som gir oss notification
