### ISSUE TITLE
Sende velkomstmail til den nylig opprettede gsuite-eposten nye teammedlemmer får når de opprettes

### ISSUE THREAD

**Issue by sigtot** [vektorprogrammet/vektorprogrammet#978]
Her kan vi ha en link til slack, blant annet.

Vi må da legge inn i slack workspacet at alle med @vektorprogrammet mailadresse kan søke om tilgang

**Comment by sondreso** [comment]
Jeg har satt på sånn at *@vektorprogrammet.no adresser kan automatisk bli med på slack nå. Det er ikke mulig å sette på at de sender invitasjon, så de blir automatisk med. 

Vet vi har diskutert dette problemet før, og da var det en liten bekymring at folk gjerne skal ha tilgang til slack litt lengre enn de er medlemmer på nettsiden. Slik som det blir nå vil de miste tilgang til mailen og derfor også muligheten til å be om nytt passord om de har glemt slack passordet. De vil derimot ikke miste tilgang til slack sammen med rettigheten på nettsiden, siden vi ikke har mulighet for å bruke SSO på slack. Så er ikke noe stort problem, man litt kluss kan det bli.

**Comment by sondreso** [comment]
Her er forresten også signup linken man kan bruke for å joine slacken om man har en vektor adresse: 
https://join.slack.com/t/vektorprogrammet/signup?x=x-89199434741-427872168615
