### ISSUE TITLE
La andreintervjuer få tilgang til å intervjue

### ISSUE THREAD

**Issue by sigtot** [vektorprogrammet/vektorprogrammet#981]
Når andreintervjuer registrerer seg selv kan en admin eller hovedintervjuer gå inn og _godkjenne_ dem, slik at de også får tilgang til å intervjue.

**Comment by kristandre** [comment]
Tror det burde gå fint om de får tilgang til å intervjue uten å bli godkjent først. Hva er risikoen?

**Comment by sigtot** [comment]
I såfall kan vel alle teammedlemmer like godt få tilgang til å intervjue by default, siden de allerede kan melde seg på som andreintervjuer selv.

**Comment by kristandre** [comment]
Ja, det åpner for at alle teammedlemmer kan assigne seg selv og utføre et intervju, men de kan ikke endre på noen andre sine intervjuer

**Comment by kristandre** [comment]
Bør da også låse slik at man ikke kan assigne seg selv til andreintervjuer etter intervjuet er gjennomført
